### PR TITLE
Windows spaced path fix

### LINKED ISSUE #80: Ctrl+C must be hit twice to kill parallel tasks
Love this! There's one quirk I'd love to figure out. I'm sending two tasks to the same command line using [npm-run-all](https://www.npmjs.com/package/npm-run-all). When I do, eslint-watch fails to be killed by the first Ctrl+C. I have to hit it twice. This only occurs on Mac. [I created a simple repo to convey the issue](https://github.com/coryhouse/eslint-watch-issue). 

It appears the first Ctrl+C kills eslint-watch, but it appears to swallow the kill signal and not pass it on to other running tasks. I can use many other tasks in parallel with npm-run-all and they all get killed when I hit Ctrl+C, so this quirk is unique to eslint-watch.

### LINKED ISSUE #84: Paths with spaces aren't supported
On Windows, if you try running eslint-watch in a path that contains spaces in the name, it will fail to parse the path properly.

Example: https://github.com/coryhouse/react-slingshot/issues/150

### PR DESCRIPTION
**Pull request by rizowski**
Fixes #84 

- Pulled out the child spawn calls to utilize more of what happened when a process exits. (Was it fatal? or was it expected)
- more debug log statements
- Also made it so that the external process will listen to the parent's stdin (might fix #80 ?)
  - Stdout and stderr are now `pipe`
- Thank god for 96% code coverage. 😄  (this might go down with the new executer script)
- Appveyor was added back in
- Watcher directory is specified to `./` if one is not provided in the optionator options.

### CODE REVIEW

**Comment by coryhouse** [comment]
Awesome! Sorry for the delay, I've been away at a conference. In order to test this, I'm referencing this branch in my package.json like this:

    "git://github.com/rizowski/eslint-watch.git#path-fix": "",

That syntax throws an error. Are you aware of an easy way for me to reference this branch in package.json?

**Comment by rizowski** [comment]
@coryhouse this should work
```
"eslint-watch": "git+https://github.com/rizowski/eslint-watch.git#path-fix"
```

**Comment by coryhouse** [comment]
Hrmm, still no luck.

| => npm install
npm ERR! git rev-list -n1 path-fix@: fatal: ambiguous argument 'path-fix@': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 path-fix@: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 path-fix@: 'git <command> [<revision>...] -- [<file>...]'

**Comment by rizowski** [comment]
How about this:
`npm i -D eslint-watch@https://github.com/rizowski/eslint-watch.git#path-fix`

**Comment by coryhouse** [comment]
@rizowski Success! The branch works with spaces in the path on Windows. 👍 

One issue: With this branch, chalk coloring doesn't come through on the output. As you can see, I lost coloring after installing the branch:
coloring lost

**Comment by rizowski** [comment]
@coryhouse The color being gone is interesting. I have noticed you can reenable it by passing `--color` Not sure what is causing it to not be defaulted yet.

**Comment by rizowski** [comment]
@coryhouse I am going to be gone for a couple of weeks. So I am going to pull this in without the color since, while color is nice, doesn't affect how the tool works. I will create an issue about the color and hopefully fix it while I am working on other things.

**Comment by rizowski** [comment]
Yeah no problem! Thanks for being a supporter! 😄

**Pull request merged**
