### PR TITLE
Check if key is defined

### PR DESCRIPTION
**Pull request by alasdairtran**
### What was the problem/Ticket Number
When the tool is running and you press a non-character key (e.g. 1, 2, 3, comma, period), the tool crashes since `key` is undefined.

### How does this solve the problem?
Add a check to make sure that `key` is defined.

### How to duplicate the issue

  1. Run the tool in watch mode
  2. Press any non-character key like 1.

### CODE REVIEW

**Comment by rizowski** [comment]
@alasdairtran Thanks for the PR! Once I get my updates in, I'll need you to update your branch and then we can get this in.

**Comment by alasdairtran** [comment]
@rizowski Thanks for merging my PR! Can you also update the package on npm as well when you have time?

**Comment by rizowski** [comment]
@alasdairtran Yeah, I will push out the version today.

**Comment by rizowski** [comment]
This has been deployed for v3.1.1

**Pull request merged**
