### PR TITLE
watch and fix

### PR DESCRIPTION
**Pull request by masarakki**

### CODE REVIEW

**Comment by rizowski** [comment]
I'll take a look at this soon. Sorry for the delay.

**Comment by rizowski** [comment]
@masarakki あなたはこの変更の告白を説明していただけますか？

**Comment by masarakki** [comment]
In the case of `esw --watch --fix`, I hope it run `esw --fix` everytime when files was updated.
But it run `--fix` only first time.

**Comment by rizowski** [comment]
@masarakki Thanks for the update, I will try to get this in soon.

**Comment by rizowski** [comment]
I was able to get it to work so I am going to merge this. Thanks for helping out. 👍

**Comment by masarakki** [comment]
thanks!!

**Pull request merged**
