### PR TITLE
Multiple extensions will apply to the watcher

### LINKED ISSUE #19: Multiple extensions do not apply to the watcher
Specifying a single extension works correctly:
```esw -w --ext .js```

However, specifying multiple extensions breaks the watcher:
```esw -w --ext .js,.jsx```

### PR DESCRIPTION
**Pull request by calvinwoo**
Fixes #19

### CODE REVIEW

**Comment by rizowski** [comment]
I'll take a look at this later this evening.

**Comment by rizowski** [comment]
It looks like it is working and tests pass. Can you update with latest dev and also stub out the console log statements in the tests?

**Comment by calvinwoo** [comment]
Unfortunately, I can't easily stub out the console.log() statements, since the Mocha reporter also relies console.log() to print out success or failure messages.

What I've done in the past is use a separate logging module instead of console.log() directly. That module would decide whether or not to call console.log() based on the presence of some environment variable.

That approach sound reasonable?

**Comment by rizowski** [comment]
I think moving the `console.log` over to a separate module like `log.js` or something of the sort, would be good. The only problem I have with having an environment variable approach is that it's introducing code that is used for testing into production code. 

If you pull `console.log` into a `log.js` file, you should be able to stub that log function from `log.js` just fine. That way you aren't stubbing `console.log` directly and you are not adding test conditionals into production code.

I don't think that needs to be done with this pull request though. This should be good as is. If you would like to you can make a pull request for pulling the logging into its own module. :smile:

**Comment by calvinwoo** [comment]
@rizowski Will do!

**Pull request merged**
