### PR TITLE
Support --ext for the watch command

### LINKED ISSUE #5: File patterns aren't respected in watch command
Currently the watch parameter only assumes that `*.js` are the files you want to watch. This needs to be able to take in what ever pattern eslint accepts.

### PR DESCRIPTION
**Pull request by calvinwoo**
This commit fixes #5

### CODE REVIEW

**Comment by rizowski** [comment]
From a glance this looks good. I will take a further look into it later this evening.

**Comment by rizowski** [comment]
When I run this locally the process exits and doesn't continue to watch the file directory. What kind of input do you feed it?

Here is some of the stuff I have given it:
`esw --ext .jst -w`

Putting a few logging entries it puts out:
```
something.jst (2/0)
  ✖  1:1  Use the global form of "use strict"            strict
  ✖  1:2  Newline required at end of file but not found  eol-last
✖ 2 errors (12:19:27 AM)

[ '.jst' ]
[ './/**/*.jst$' ]
Watching ./

➜  eslint-watch git:(pr/12) ✗
```

I am pretty sure it has something to do with `pathToWatch` being added to the watch command when it is the default path. Default path shouldn't be added to the watcher unless it is specified as something other than default.

**Comment by calvinwoo** [comment]
@rizowski 
Strange, I'm not able to reproduce the error you seem to be getting. What steps did you go through to get that error?

I tried to do the cleanest test possible:
1. ```npm init``` in a new folder
2. ```npm install --save https://github.com/calvinwoo/eslint-watch.git```
3. Add the npm script: ```"lint": "esw -w --ext .jst"``` to ```package.json```
4. Add ```.eslintrc``` with rules
5. Add ```something.jst``` as a test file
6. Execute ```npm run lint```
7. Modify ```something.jst```

**Comment by rizowski** [comment]
Hmm yeah I am still having it exit immediately. What environment are you running this on? I am currently trying it on windows. I can try it on my mac to see if that makes a difference.

This is what I did:
esw

**Comment by calvinwoo** [comment]
Cool, I was able to reproduce your issue on Windows; I was running it on OSX earlier.

**Comment by rizowski** [comment]
Ok that looks to be working now. Can you recreate this PR and point to dev?

**Comment by calvinwoo** [comment]
Will do.

**Pull request closed without merging**
